# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_generation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15text_generation.proto\x12\x0etextgeneration\"\"\n\x11GenerationRequest\x12\r\n\x05start\x18\x01 \x01(\t\")\n\x12GenerationResponse\x12\x13\n\x0boutput_text\x18\x01 \x01(\t2p\n\x15TextGenerationService\x12W\n\x0cGenerateText\x12!.textgeneration.GenerationRequest\x1a\".textgeneration.GenerationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_generation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERATIONREQUEST._serialized_start=41
  _GENERATIONREQUEST._serialized_end=75
  _GENERATIONRESPONSE._serialized_start=77
  _GENERATIONRESPONSE._serialized_end=118
  _TEXTGENERATIONSERVICE._serialized_start=120
  _TEXTGENERATIONSERVICE._serialized_end=232
# @@protoc_insertion_point(module_scope)
